// What the Telegram bot says, in the app's three languages. {placeholders} are filled by logic.js fill().
"use strict";

module.exports = {
  ru: {
    hello: "Это Қalta: запись трат одной фразой.\n\nЧтобы подключить, откройте приложение → Настройки → Telegram-бот → Подключить. Записи появятся в приложении на всех ваших устройствах.",
    linked: "Готово, бот подключён.\n\nПишите одной фразой: «кофе 2800», «вчера такси 1 500 наличными», «+420 000 зарплата».\n/month — месяц, /today — сегодня, /undo — отменить последнее, /stop — отключить.",
    badLink: "Ссылка устарела или уже использована. Откройте в приложении Настройки → Telegram-бот и нажмите «Подключить» ещё раз.",
    stopped: "Бот отключён от вашего аккаунта. Записи остались в приложении.",
    help: "Пишите одной фразой: «кофе 2800», «вчера такси 1 500 наличными», «+420 000 зарплата», «2,5к продукты».\n/month — месяц, /today — сегодня, /undo — отменить последнее, /stop — отключить.",
    noAmount: "Не вижу суммы. Например: «кофе 2800».",
    tooBig: "Сумма больше 999 999 999 — проверьте фразу.",
    future: "Дата во фразе в будущем — такую запись сделать нельзя.",
    saved: "✅ {cat} {amount} · {when} · {pay}",
    ask: "Куда записать {amount}{what}?",
    pickCat: "Выберите категорию для {amount}:",
    undone: "↩️ Отменено: {cat} {amount}",
    notSaved: "Не записано.",
    gone: "Этой записи уже нет.",
    undoBtn: "↩️ Отменить", catBtn: "Категория", cancelBtn: "Отмена",
    nothingToUndo: "Отменять нечего.",
    month: "{month}: потрачено {spent}, доход {income}.",
    monthBudget: "Бюджет {budget}: осталось {left} — это ≈ {perDay} в день на {days} дн.",
    monthOver: "Бюджет {budget} превышен на {over}.",
    top: "Больше всего: {list}.",
    today: "Сегодня: {n} — {spent}.",
    todayNone: "Сегодня записей нет.",
    limit: "На сегодня записей через бота слишком много. Завтра снова можно.",
    failed: "Не получилось записать, попробуйте ещё раз через минуту.",
    today_w: "сегодня", yesterday_w: "вчера", card: "карта", cash: "наличные"
  },
  kz: {
    hello: "Бұл Қalta: шығынды бір жолмен жазу.\n\nҚосу үшін қосымшаны ашыңыз → Баптаулар → Telegram-бот → Қосу. Жазбалар барлық құрылғыларыңызда пайда болады.",
    linked: "Дайын, бот қосылды.\n\nБір жолмен жазыңыз: «кофе 2800», «кеше такси 1 500 қолма-қол», «+420 000 жалақы».\n/month — ай, /today — бүгін, /undo — соңғысын болдырмау, /stop — ажырату.",
    badLink: "Сілтеменің мерзімі өткен немесе қолданылған. Қосымшада Баптаулар → Telegram-бот → «Қосу» батырмасын қайта басыңыз.",
    stopped: "Бот аккаунтыңыздан ажыратылды. Жазбалар қосымшада қалды.",
    help: "Бір жолмен жазыңыз: «кофе 2800», «кеше такси 1 500 қолма-қол», «+420 000 жалақы».\n/month — ай, /today — бүгін, /undo — соңғысын болдырмау, /stop — ажырату.",
    noAmount: "Соманы көрмеймін. Мысалы: «кофе 2800».",
    tooBig: "Сома 999 999 999-дан асады — сөйлемді тексеріңіз.",
    future: "Сөйлемдегі күн болашақта — мұндай жазба жасауға болмайды.",
    saved: "✅ {cat} {amount} · {when} · {pay}",
    ask: "{amount}{what} қайда жазылсын?",
    pickCat: "{amount} үшін санатты таңдаңыз:",
    undone: "↩️ Болдырылмады: {cat} {amount}",
    notSaved: "Жазылмады.",
    gone: "Бұл жазба енді жоқ.",
    undoBtn: "↩️ Болдырмау", catBtn: "Санат", cancelBtn: "Бас тарту",
    nothingToUndo: "Болдырмайтын ештеңе жоқ.",
    month: "{month}: жұмсалды {spent}, кіріс {income}.",
    monthBudget: "Бюджет {budget}: қалды {left} — {days} күнге күніне ≈ {perDay}.",
    monthOver: "Бюджет {budget} {over} асып кетті.",
    top: "Ең көбі: {list}.",
    today: "Бүгін: {n} — {spent}.",
    todayNone: "Бүгін жазба жоқ.",
    limit: "Бүгін бот арқылы жазба тым көп. Ертең қайта болады.",
    failed: "Жазу мүмкін болмады, бір минуттан кейін қайталап көріңіз.",
    today_w: "бүгін", yesterday_w: "кеше", card: "карта", cash: "қолма-қол"
  },
  en: {
    hello: "This is Қalta: log spending in one line.\n\nTo connect, open the app → Settings → Telegram bot → Connect. Entries appear in the app on all your devices.",
    linked: "Done, the bot is connected.\n\nWrite one line: \"coffee 2800\", \"yesterday taxi 1,500 cash\", \"+420,000 salary\".\n/month — this month, /today — today, /undo — undo the last one, /stop — disconnect.",
    badLink: "This link has expired or was used. In the app open Settings → Telegram bot and tap Connect again.",
    stopped: "The bot is disconnected from your account. Your entries stay in the app.",
    help: "Write one line: \"coffee 2800\", \"yesterday taxi 1,500 cash\", \"+420,000 salary\".\n/month — this month, /today — today, /undo — undo the last one, /stop — disconnect.",
    noAmount: "I see no amount. For example: \"coffee 2800\".",
    tooBig: "The amount is over 999,999,999: check the line.",
    future: "The date in the line is in the future: that cannot be recorded.",
    saved: "✅ {cat} {amount} · {when} · {pay}",
    ask: "Where should {amount}{what} go?",
    pickCat: "Choose a category for {amount}:",
    undone: "↩️ Undone: {cat} {amount}",
    notSaved: "Not recorded.",
    gone: "This entry is no longer there.",
    undoBtn: "↩️ Undo", catBtn: "Category", cancelBtn: "Cancel",
    nothingToUndo: "Nothing to undo.",
    month: "{month}: spent {spent}, income {income}.",
    monthBudget: "Budget {budget}: {left} left — about {perDay} a day for {days} days.",
    monthOver: "Budget {budget} exceeded by {over}.",
    top: "Most: {list}.",
    today: "Today: {n} — {spent}.",
    todayNone: "Nothing recorded today.",
    limit: "Too many entries through the bot today. Tomorrow it works again.",
    failed: "Could not record that, try again in a minute.",
    today_w: "today", yesterday_w: "yesterday", card: "card", cash: "cash"
  }
};
