// Dev tool: downloads the Phosphor icons the app uses and writes src/icons.js.
//   node tools/gen-icons.js
// Phosphor Icons are MIT licensed (https://github.com/phosphor-icons/core). The
// version is pinned; the generated file is committed, so the app never fetches
// icons at runtime. Each icon is a single filled path in a 256x256 box, which is
// what lets the template bind it as d="{{ path }}".
const fs = require("fs");
const path = require("path");

const VERSION = "2.1.1";
const BASE = "https://unpkg.com/@phosphor-icons/core@" + VERSION + "/assets/";

// name -> weights wanted ("regular", "fill")
const R = ["regular"], F = ["fill"], RF = ["regular", "fill"];
const WANT = {
  // navigation / chrome
  "house": RF, "clock-counter-clockwise": RF, "handshake": RF, "gear-six": RF,
  "plus": ["bold"], "x": ["bold"], "caret-right": ["bold"], "caret-left": ["bold"], "caret-down": ["bold"], "check": ["bold"],
  "trash": R, "pencil-simple": R, "magnifying-glass": R, "backspace": R, "arrow-counter-clockwise": R,
  "calendar-blank": R, "note-pencil": R, "credit-card": R, "money": R, "wallet": R, "target": R, "translate": R,
  "sun": R, "moon": R, "palette": R, "download-simple": R, "upload-simple": R, "user-circle": R, "google-logo": R,
  "sign-out": R, "cloud-check": R, "cloud-slash": R, "warning-circle": R, "info": R, "dots-six-vertical": ["bold"],
  "dots-three": ["bold"], "coins": R, "arrow-up-right": ["bold"], "arrow-down-left": ["bold"], "piggy-bank": R,
  "bank": R, "shield-check": R, "lock-simple": R, "clock": R, "repeat": R, "tag": R, "list-bullets": R, "sliders-horizontal": R,
  // category glyphs (filled, white on a coloured tile)
  "shopping-cart": F, "bus": F, "coffee": F, "house-line": F, "lightbulb": F, "wifi-high": F, "device-mobile": F,
  "pill": F, "stethoscope": F, "t-shirt": F, "sneaker": F, "baby": F, "backpack": F, "barbell": F, "scissors": F,
  "gift": F, "film-slate": F, "taxi": F, "gas-pump": F, "wrench": F, "squares-four": F, "briefcase": F, "laptop": F,
  "key": F, "percent": F, "arrow-u-up-left": F, "plus-circle": F, "airplane-tilt": F, "paw-print": F, "book-open": F,
  "game-controller": F, "music-notes": F, "fork-knife": F, "wine": F, "bicycle": F, "car": F, "train": F, "heartbeat": F,
  "tooth": F, "plant": F, "bed": F, "couch": F, "hand-heart": F, "flower": F, "paint-brush": F, "camera": F,
  "desktop": F, "headphones": F, "tent": F, "umbrella": F, "bowl-food": F, "hamburger": F, "pizza": F, "ice-cream": F,
  "beer-stein": F, "shopping-bag": F, "storefront": F, "receipt": F, "graduation-cap": F, "first-aid-kit": F,
  "dog": F, "cat": F, "tree": F, "sparkle": F, "star": F, "heart": F, "basket": F, "money-wavy": F, "coins-fill": F,
  "credit-card-fill": F, "wallet-fill": F, "bank-fill": F, "piggy-bank-fill": F, "calendar-fill": F
};

function file(name, weight) {
  const suffix = weight === "regular" ? "" : "-" + weight;
  return BASE + weight + "/" + name + suffix + ".svg";
}

async function one(name, weight) {
  const res = await fetch(file(name, weight));
  if (!res.ok) return { error: res.status };
  const svg = await res.text();
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  const other = /<(circle|rect|line|polyline|polygon|ellipse)\b/.test(svg);
  if (!paths.length || other) return { error: "unsupported shapes" };
  return { d: paths.join(" ") };
}

(async () => {
  const out = {};
  const missing = [];
  const jobs = [];
  for (const [name, weights] of Object.entries(WANT)) {
    for (const w of weights) jobs.push({ name, w });
  }
  // modest parallelism
  let i = 0;
  async function worker() {
    while (i < jobs.length) {
      const job = jobs[i++];
      const r = await one(job.name, job.w);
      if (r.error) { missing.push(job.name + ":" + job.w + " (" + r.error + ")"); continue; }
      (out[job.name] = out[job.name] || {})[job.w[0] === "r" ? "r" : job.w[0] === "f" ? "f" : "b"] = r.d;
    }
  }
  await Promise.all(Array.from({ length: 8 }, worker));

  const names = Object.keys(out).sort();
  const body = names.map(n => "  " + JSON.stringify(n) + ": " + JSON.stringify(out[n])).join(",\n");
  const header = "// GENERATED by tools/gen-icons.js — do not edit.\n" +
    "// Phosphor Icons " + VERSION + ", MIT License, Copyright (c) 2020 Phosphor Icons (https://phosphoricons.com).\n" +
    "// Keys: r = regular, f = fill, b = bold. Each value is one SVG path (viewBox 0 0 256 256).\n";
  fs.writeFileSync(path.join(__dirname, "..", "src", "icons.js"), header + "module.exports = {\n" + body + "\n};\n");
  console.log("icons written:", names.length, "names");
  if (missing.length) console.log("MISSING:\n  " + missing.join("\n  "));
})();
